- project:
    templates:
      - openstack-cover-jobs
      - release-notes-jobs-python3
      - publish-openstack-docs-pti
    check:
      jobs:
        - openstack-tox-pep8
        - openstack-tox-py36
        - openstack-tox-py37
        - openstack-tox-py38
        - openstack-tox-py39
    gate:
      jobs:
        - openstack-tox-pep8
        - openstack-tox-py36
        - openstack-tox-py37
        - openstack-tox-py38
        - openstack-tox-py39
