- project:
    templates:
      - openstack-cover-jobs
      - openstack-python-jobs
      - openstack-python36-jobs
      - openstack-python37-jobs
      - release-notes-jobs-python3
      - publish-openstack-docs-pti
